services:
  postgres:
    container_name: postgres
    image: postgres:17
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: irmazda
      POSTGRES_PASSWORD: test
      POSTGRES_DB: irmazda
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - gm
  
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.6
    container_name: keycloak
    command:
      - start-dev
      - --import-realm
      # - --spi-theme-default=notifyme_theme
    # env_file:
    #   - .env
    # depends_on:
    #   - db_keycloak
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./kc/:/opt/keycloak/data/import/
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_REALM=irmazda
    ports:
      - "8080:8080"


volumes:
  postgres:
    driver: local
  keycloak_data:
    driver: local

networks:
  gm:
    driver: bridge
