services:
  postgres:
    container_name: postgres
    image: postgres:17
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - gm

volumes:
  postgres:
    driver: local

networks:
  gm:
    driver: bridge