server:
  port: 8081

logging:
  level:
    org:
      springframework:
        security: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/irmazda
    username: irmazda
    password: test
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8080/realms/irmazda"

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
