server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/irmazda
    username: irmazda
    password: test
    
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
