server:
  port: 8081

logging:
  level:
    org:
      springframework:
        security: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/irmazda
    username: irmazda
    password: test
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8080/realms/irmazda"

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

keycloak:
  auth-server-url: http://localhost:8080
  realm: irmazda
  admin-cli:
    client-id: admin-cli
    client-secret: AXFGM1Q1ABIVb4tcqkJBZmFX8EdriFJt

cloudinary:
  cloud_name: dkgkrplvp
  api_key: 845356959256984
  api_secret: KY2K-0alMxl_QMXKOOScOgLxqLU
  upload:
    preset: irmazda
